# Generated by Django 4.2.3 on 2023-07-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='coupe_number',
        ),
        migrations.AddField(
            model_name='trainticket',
            name='coupe_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
