# Generated by Django 4.2.3 on 2023-07-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_remove_train_coupe_number_trainticket_coupe_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelreservation',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='hotelreservation',
            name='check_out_date',
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_in_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_date',
            field=models.DateTimeField(null=True),
        ),
    ]
